### ISSUE TITLE
Choose and add logging to the project

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#11]
I've only ever used log4j for logging and javascript seems to have a version:

http://log4javascript.org

Has anyone used anything better?

**Comment by timack** [comment]
- [ ] Investigate: https://www.npmjs.com/package/winston
- [ ] Investigate: http://log4javascript.org/

**Comment by timack** [comment]
I've added in Winston. Notes on Wiki.
BTW - you can also use javascripts `console` on the backend for basic logging as well.
