### ISSUE TITLE
Add 3:1 and 2:1 trading when harbours introduced.

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#119]
The current trading has 4:1 trading enabled.  3:1 and 2:1 can be added when the harbours are introduced into the game.

**Comment by Luke-Nukem** [comment]
Must fix issue #114 for this to be done.

**Comment by Luke-Nukem** [comment]
Issue #114 is fixed by MR  #139, harbours should now be able to be introduced in to the game.
