### ISSUE TITLE
Invite Henning and Jens to our Google Doc, Slack and Github accounts

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#12]
If they are going to be marking our work / overseeing everything, they should have access

**Comment by timack** [comment]
I think @unshorn has access to all of the above. Does Henning need access too @unshorn?

**Comment by unshorn** [comment]
I'll ask @timack

**Comment by timack** [comment]
@unshorn I've not heard back so assuming ok to close this?
