### ISSUE TITLE
Script Selenium Interface Tests

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#136]
Create scripts to test the interface using Selenium
Prescript dicerolls so gameplay is predictable

**Comment by sumnerfit** [comment]
Pre-scripted dice rolls sorted.

**Comment by timack** [comment]
@fishinsea2014 Whats the update on this?

**Comment by timack** [comment]
@fishinsea2014 How's things going with this?

**Comment by timack** [comment]
@fishinsea2014 Can you give me a status update on this before I flip my lid.

**Comment by timack** [comment]
@fishinsea2014 if you don’t give me an update in the next hour @sumnerfit will be taking over the headless browser testing.

**Comment by timack** [comment]
@sumnerfit This is now yours @fishinsea2014 isn't responding and at this stage we need some certainty on what going on.

**Comment by timack** [comment]
@sumnerfit thanks for sorting this out at short notice. First cut of headless testing is now on master - additional tests will need to be written later but we can take a look at that post week 8.
