### ISSUE TITLE
End game issues

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#158]
I'm not sure if these are recognised and this is a duplicate or not implemented yet..

On game end, I don't have the settlements counted in the final score sheet 

![image](https://user-images.githubusercontent.com/22135017/30305109-368b0d68-97c5-11e7-82a0-0c0e1b6e4329.png)
(Winners screen)

and the loser doesn't have their board updated with the winners moves.
![image](https://user-images.githubusercontent.com/22135017/30305145-556948da-97c5-11e7-904e-f0c81c94555f.png)
(Losers screen)

**Comment by Luke-Nukem** [comment]
Fixed in PR #221
