### ISSUE TITLE
Other players in top corner aren't populated correctly

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#165]
When playing 4 player, the icons used to show other players haven't finished are all in player 2's box

![image](https://user-images.githubusercontent.com/22135017/30503539-bbf068ee-9abe-11e7-833d-e3d0282e694d.png)

**Comment by timack** [comment]
@akclint Is this resolved now? Can we close this issue?

**Comment by sumnerfit** [comment]
Alayn fixed this up
