### ISSUE TITLE
Dev card rules modal button unreachable

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#174]
Button to close modal appears off the bottom of the screen.

![image](https://user-images.githubusercontent.com/1098068/30534186-28e9ebde-9cb1-11e7-9e31-b37ee63d5a4f.png)

**Comment by sumnerfit** [comment]
Modal now scrollable if it passes off the bottom of screen and resized large card to bring button on to screen for majority of screen resolutions.

(On 1024x768):
![image](https://user-images.githubusercontent.com/22135017/30682484-f3319ede-9efd-11e7-81b1-668ae13a706e.png)
