### ISSUE TITLE
Check dice roll statistics

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#177]
Dice rolls don't feel random enough (or it could be my imagination).  Add a test to check dice roll results are close to:

![image](https://user-images.githubusercontent.com/22135017/30589521-e6d09e12-9d8e-11e7-8cd0-db08df8c4884.png)

**Comment by akclint** [comment]
Spot on with 10,000 rolls:

[ 0, 0, 287, 564, 832, 1137, 1399, 1682, 1325, 1120, 822, 577, 255 ]
