### ISSUE TITLE
Can't see number of knights I have

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#184]
I've just purchased 2 Knight Cards but only see on displayed - as a quick fix could we put a number on top of the card if we have more than one card of the same type?

![image](https://user-images.githubusercontent.com/1098068/30687630-05c87330-9f10-11e7-89a7-48b34b57e2f0.png)

**Comment by Luke-Nukem** [comment]
Data will need to be added within `player.js`:

```
function Player(socket, data) {
    // trimmed out data
    this.score          = {
      total_points   : 0,
      victory_points : 0,
      road_length    : 0,
      settlements    : 0,
      cities         : 0,
      longest_road   : false,
      largest_army   : false
    };
    // trimmed out data
}
```
