### ISSUE TITLE
Starting game with new players gets stuck.

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#191]
Loading up games in browser tabs sometimes as both browsers saying "1 of 2" or one says "waiting for others to place settlements" and the other says "waiting for other players"

**Comment by timack** [comment]
I'm having trouble reliably replicating this issue.

**Comment by Luke-Nukem** [comment]
Should be solved by issue #241 when completed.

**Comment by Luke-Nukem** [comment]
Fixed by the lobby update in PR #249
