### ISSUE TITLE
The points in the winners end game modal differ from top left corner.

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#216]
When the game ends, the window displaying the winner's scores are the scores that the game ends with.  These scores are not reflected in the scores in the top left corner...

I saw the modal come up and checked top left first and that showed no one had won, then checking the main window, Tim snuck home.

![image](https://user-images.githubusercontent.com/22135017/30781926-e6ba97e4-a184-11e7-8d55-e3dbcc21ed0b.png)

**Comment by Luke-Nukem** [comment]
Is part of issue #238

**Comment by Luke-Nukem** [comment]
Accidentally closed.

**Comment by Luke-Nukem** [comment]
Should be fixed in PR #255
