### ISSUE TITLE
Top left finish turn spinners reset? 

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#217]
Example: Jason had finished his turn and had the tick beside his name. Alayn and Tim had spinners and were still in their turn sequence.  I finished my turn, that set Jason's tick icon back to a spinner icon.  When Alayn finished, both Alayn and Jason's spinners switched to ticks.

**Comment by timack** [comment]
@akclint Should this one be closed?

**Comment by timack** [comment]
@akclint See above .. can we close this one?

**Comment by Luke-Nukem** [comment]
Fixed in PR #325
