### ISSUE TITLE
Licences etc...

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#218]
Should we have a space somewhere (maybe start page) that has a list of licenses (if any) and links to any software / resources we use (if we ad sound effects etc...)

**Comment by Luke-Nukem** [comment]
This is critical, we need to list which licenses are used by which libraries, and work out which license we need for the game. Is it going to be open source? Proprietary etc?

Personally I like the [MPL](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) (Mozilla) license which is a good blend between the MIT/Apache licenses and the GPL license. 

The [https://choosealicense.com/](https://choosealicense.com/) website is a good starting point.

**Comment by sumnerfit** [comment]
I haven't looked into licences much wrt gaming. Would it have any bearing on our commercialisation strategy.

⁣-----------
Craig Walker
Coded!  - Kiwis coding the world.
03 755 8323

**Comment by timack** [comment]
Have added MPL to master.

**Comment by Luke-Nukem** [comment]
Nice, MPL I think is a good fit. Allows commercialisation and open source distribution, while affording a number of protections.

We can:
* use the code for commercial ventures, like running a server game
* distribute the source, and enforce contributions back to the source
  - additionally we can append proprietary code to our product and not have conflicts
  - we can use proprietary libraries and third-party parts without violating the MPL
* we are protected with IP and patent clauses
