### ISSUE TITLE
Victory Point Card not received from server

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#229]
Victory point development card shows as purchased from the server but never gets delivered to the client side (even on next turn)

**Comment by sumnerfit** [comment]
Also, trying to recreate the issue, I get:
![image](https://user-images.githubusercontent.com/22135017/30838051-c24f646a-a2c5-11e7-9df2-f0db6a51cc4d.png)

**Comment by Luke-Nukem** [comment]
Does the score increase though?

**Comment by Luke-Nukem** [comment]
Looks to have been fixed
