### ISSUE TITLE
Longest road should have been awarded to craig

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#235]
![image](https://user-images.githubusercontent.com/1098068/30903140-37b78a52-a3ca-11e7-8ab9-8ae5c2a1c6ac.png)

**Comment by Luke-Nukem** [comment]
I recall it did. Points aren't awarded until round is complete.
Maybe we can book a time to have another game?

**Comment by timack** [comment]
Yep good idead

**Comment by sumnerfit** [comment]
Henning was watching my screen as I'd built the 5th road and told him I'd receive longest road in the next turn.  I didn't get it.

... possibly sneaky Alayn had built 5 too, I was watching other players and hadn't noticed him.  I built another road (now 6) and received it.

**Comment by Luke-Nukem** [comment]
@sumnerfit I also built a road of 5. If I recall the code prevents any player recieving the bonus if two longest roads are built in the same turn.

We do need to test 4 players while interfacing in slack.

**Comment by timack** [comment]
This appears to be working correctly.
