### ISSUE TITLE
Feature: Implement game lobby

### ISSUE THREAD

**Issue by Luke-Nukem** [159356-1702-Extramural/capstone#241]
To help aleviate issues with joining games, a game lobby will be implemented:

1. On first visit to website new players will be shown a page to enter a name and click "Join Game"
2. The player is then taken to a new page that displays current games and their details:
    * Is game full?
    * How many players waiting?
    * Max players
    * Player names
    * Game name + ID number
3. When a player clicks a non-full game they will then join that game
    * server side will check the player actually can join the game, if full then it sends back a 'game_full' emit on the socket + new games data
4. Or they can click the "New Game" button
    * this takes the player to a new setup screen to add a game name, and player amount [2-4]
    * the player amount will be passed to the server via `/?players=num`

@akclint can you edit this comment to add any details you see as important please?

**Comment by Luke-Nukem** [comment]
@akclint server side stuff is [in this branch](https://github.com/159356-1702-Extramural/capstone/tree/experimental/lobby). You will want to merge in to your own branch I think. Should be easy to see what's been added in the diff.

**Comment by timack** [comment]
Can the player start a new game?

**Comment by Luke-Nukem** [comment]
I knew I forgot something.

**Comment by Luke-Nukem** [comment]
Implemented in PR #249
