### ISSUE TITLE
Dice Roller

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#25]
@fishinsea2014 In the project can you create a function that simulates the rolling of 2 six sided dice and returns the result in the object that gets returned at the end of each round.

Maybe add a a new function in the game.js file

Please use process as outlined in wiki but please don't merge in your branch assign the Pull Request to me.

**Comment by fishinsea2014** [comment]
Yes, I can do that.

**Comment by timack** [comment]
@fishinsea2014 Let me know if you have any issues or get stuck

**Comment by fishinsea2014** [comment]
Ok, thank you.

**Comment by fishinsea2014** [comment]
Should the result of the rolling of 2 dice be evenly distributed between 2-12?

**Comment by timack** [comment]
Definitely not. I'm glad you asked. The gameplay depends on the dice roll result distribution simulating rolling two dice. i.e a 7 would be the most likely result [1,6][2,5][3,4][4,3][5,2][6,1] whereas 2 and 12 would be the least likely as they can only be achieved by rolling [1,1] and [6,6].

**Comment by timack** [comment]
![image](https://user-images.githubusercontent.com/1098068/28806183-a941c9d8-76c2-11e7-9f80-a9d96fedfd57.png)

Roll odds are actually in the game rule book ...

**Comment by timack** [comment]
@fishinsea2014 How are you getting on with this?

**Comment by fishinsea2014** [comment]
I am working on this.

**Comment by timack** [comment]
@fishinsea2014 Also for good house keeping close off the issue you were working on when has been merged into master.
