### ISSUE TITLE
Trading error

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#256]
Started with 5 lumber and 0 brick. Traded 4:1 Lumber for brick ended up with 2 of each
![image](https://user-images.githubusercontent.com/22135017/31004455-02aac60c-a551-11e7-9075-1e083c33ea1e.png)

**Comment by Luke-Nukem** [comment]
Seems to be fixed. Will close - please reopen if you catch the bug again.
