### ISSUE TITLE
VP card sent twice

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#257]
Purchased 2 dev cards in a turn, awarded chapel on first purchase, received monopoly on second purchase, but also was shown first VP card again.

Below image shows client on left and server console in debug on right

![image](https://user-images.githubusercontent.com/22135017/31005245-540870dc-a554-11e7-8132-58f3c099b3a3.png)

**Comment by Luke-Nukem** [comment]
This is a client side bug. @akclint any ideas?
