### ISSUE TITLE
Change cursor when hovering over interactive elements

### ISSUE THREAD

**Issue by Luke-Nukem** [159356-1702-Extramural/capstone#277]
Some feedback I got was that it isn't obvious that you can click on cards. A solution to this would be to add a cursor change to `catan.css`.

I think the `.cards .card, .failed_card .card {` and `.dev_rules {` locations are good places for the cursor change.

**Comment by timack** [comment]
Also when Knight card disabled I think there is a cursor style to indicate disabled

**Comment by Luke-Nukem** [comment]
Shit, I commited to master and pushed without thinking. It's solid, though....
