### ISSUE TITLE
Robot Player

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#279]
Create computer player(s) for people to play against.

**Comment by timack** [comment]
I've created this as an 'Epic' please create smaller subtasks for this as you uncover more about the approach you want to take.

**Comment by timack** [comment]
@fishinsea2014 can we please get an update on where you are up to with this.

**Comment by fishinsea2014** [comment]
Hi, Tim.
I have been working on my Intelligence Machine assignment for last four days.
I am doing the coding for now and will keep update every day.

**Comment by timack** [comment]
@fishinsea2014 can you keep your development branch updated on Github so we can see your progress. Also could you break down what you are doing into small github issues and put them inside this 'epic' - let me know if you're not clear on anything.

**Comment by timack** [comment]
@fishinsea2014 Please can you make sure you add you smaller issues to this epic today please.

**Comment by timack** [comment]
@fishinsea2014 Please respond to the above ⬆️

**Comment by fishinsea2014** [comment]
Keep moving with the help of Craig.

**Comment by fishinsea2014** [comment]
Stuck on add actions to the computer player.

**Comment by timack** [comment]
@fishinsea2014 have you discussed with @sumnerfit - also I asked if you could break down what you're doing into smaller issues.

**Comment by timack** [comment]
@fishinsea2014 ⬆️

**Comment by timack** [comment]
As per discussion last night we wont continue with this feature.
