### ISSUE TITLE
Robber placement logic - target player in lead

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#284]
For game balancing we need to increase the probability the the robber will affect the player(s) that is current in the lead.

**Comment by Luke-Nukem** [comment]
Adding myself to this as I have an idea in conjunction with dice.

* It would be preferable to have the robber target only one player (randomly)
* The last person robbed is assigned the robber
    + When the robber is next moved, this person get's the robbed resource
* If a knight is played, those rules apply
    + Played knight then blocks the robber for a round.
* Rules say that when a 7 is rolled, _all_ players with over 7 cards must discard half (keep this).

**Comment by Luke-Nukem** [comment]
Issue targetted in PR #321
