### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#3]

**Comment by sumnerfit** [comment]
I think "use cases" will be helpful to get us all thinking the same way but would be very simplistic
e.g.
![image](https://user-images.githubusercontent.com/22135017/28511739-904799f6-70a2-11e7-95ea-592a7e641ce9.png)

Having something like this:
![image](https://user-images.githubusercontent.com/22135017/28512008-167908a6-70a4-11e7-8a25-a0e5f222882a.png)
adapted from the discussions we all have around the gameplay notes Alayn and I are putting togther.

and from that building "essential use cases" which could be as the name says essential to quickly flesh out how this programme will run from start to finish.
e.g.
From Mr Paul Lyons (158.360)
http://www-ist.massey.ac.nz/plyons/158.360/Essays/3a%20EUCs/EUCs%20Have%20Their%20Own%20Format.htm

**Comment by sumnerfit** [comment]
From the Week 4 report guidelines:
> It is recommended to use use case diagrams and descriptions for this purpose. This will define the scope of the project. Also list explicitly what is outside the scope of the project.  Prioritize requirements.  Describe when each requirement will be supported by your product. It is highly recommended to build a functional product first that supports only a subset of the original requirements!

My thoughts are having a graph as above, the essential use cases (also above) and the timeline (see project life cyle investigation - https://github.com/159356-1702-Extramural/capstone/issues/4) would be enough to be able to write and answer the above question.

**Comment by sumnerfit** [comment]
I've built the first Essential Use Case
https://drive.google.com/open?id=131j4z8t73p6dnZxLe9VDl0kbwTppsaX0h7t84ok1skw

I'll get to work on the others tomorrow

**Comment by sumnerfit** [comment]
Can we close this?
