### ISSUE TITLE
Bringing up other popups in setup disables Finish Turn

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#306]
I chose to have a look at "Card Rules" during setup and when I closed the popup, the finish turn button became disabled.

![image](https://user-images.githubusercontent.com/22135017/31254740-681d0ee8-aa86-11e7-8ae9-b617672c1bb4.png)

**Comment by timack** [comment]
I wonder id this is related to my fix to stop the multiple clicking when starting game - might need a more target class name to deactivate those buttons.

**Comment by Luke-Nukem** [comment]
I've added some small checks serverside to prevent a player doing anything except accept a trade if their turn is complete. This just needs to be addressed clientside now.
