### ISSUE TITLE
Dice Roll Issues

### ISSUE THREAD

**Issue by akclint** [159356-1702-Extramural/capstone#312]
The dice rolls (for the fixed rolls) have a couple of issues:
1 - 2,3,4,11,12 never roll
2 - During the first 36 rounds, the sequence is always 5,6,7,8,9,10 (when the robber is active)
3 - The split between the rolling numbers is almost exactly an even distribution (probably because of 2 above)

From the looks of the code, it has to do with the dice1array that is created initially.  It is missing a lot of the possible dice combinations:

[[1,4], [2,4], [3,4], [4,4], [5,4], [6,4]];

Instead of:

[[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[2,1],[2,2],[2,3],[2,4],[2,5],[2,6],[3,1],[3,2],[3,3],[3,4],[3,5],[3,6],[4,1],[4,2],[4,3],[4,4],[4,5],[4,6],[5,1],[5,2],[5,3],[5,4],[5,5],[5,6],[6,1],[6,2],[6,3],[6,4],[6,5],[6,6]];

**Comment by sumnerfit** [comment]
Fixed dice rolls is used for testing to take variation out of rolls. It's supposed to be a small subset of dice roll numbers just to let the game advance a few turns and have known outcomes.

It should just cycle through those 6 numbers over and over.
