### ISSUE TITLE
Trade Button behaviour

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#313]
I found this quite weird how the same button could cause different behaviour, sometimes you'd get three sub buttons (screenshot below), sometimes you'd go direct into interplayer trade, sometime you'd get a help modal.

![image](https://user-images.githubusercontent.com/1098068/31302269-e6417904-ab5c-11e7-8828-50db3c328463.png)

It might make more sense to just disable the unavailable options so the user doesn't get confused - we use the same patter in other parts of the ui - eg. buy dev card / finish turn

![image](https://user-images.githubusercontent.com/1098068/31302276-ee0ddd76-ab5c-11e7-8f69-071a86ee5b07.png)

**Comment by Luke-Nukem** [comment]
Fixed in PR #325
