### ISSUE TITLE
Can't cancel a trade offer

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#316]
Say you change your mind you can't cancel the trade offer.

**Comment by Luke-Nukem** [comment]
Functionality is there on the server side to do so. Just needs the client to send a packet with data_type = 'cancel_player_trade' + their id. See `StateMachine.prototype.cancel_player_trade = function (data)`

**Comment by Luke-Nukem** [comment]
Fixed in PR #325
