### ISSUE TITLE
Start up sequence

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#34]
Select a player at random
Disable other player controls
Allow selected player to put down a house and road
Update players boards as placement is confirmed
Move on to next player and repeat. 
Until all players have placed 2 settlements and 2 roads
Validate legal move front and back end
Sequence of play (assuming player one starts): [1,2,3,4,4,3,2,1]

**Comment by timack** [comment]
Start up sequence needs a couple of modal windows and done (depends on data api)

**Comment by Luke-Nukem** [comment]
Relies on the data exchange API being in place.
Is also part of server side game logic as the server will direct this somewhat.

**Comment by timack** [comment]
After chat with @sumnerfit plan is to do the following for now:
- [ ] Get up to date with current master
- [ ] Clean up modals

Then will get that onto master. The next update will need to wait for @Luke-Nukem's part so we can validate the moves, sent the data to server and get back the updated game state.

**Comment by Luke-Nukem** [comment]
Just some quick notes:

On player connecting to the game, this is run in `app/app.js`;
```
    socket.on('join_request', function(data) {
        logger.log('info', 'Join Request');
        games.assign_player(socket, data);
    });
```
data here is expected to be full details for the player only, per the API, nothing else is needed (no cards, action, etc).

From there the server will add the player to a game then once there is enough players, send back a packet of data which contains the board + details of each player (name, colour etc, per the API).

Once that is received by clients, they send back the "setup" packet. Basically the "setup" action (`data_type`), plus where they've put settlements/roads. I understand this will be an iterating sequence? eg, `[0,1,2,3,3,2,1,0]` on server side? The server for each player in turn will send a responding "setup" `data_type`.

Once setup is complete, the server will send a "setup_complete" `data_type` packet, consisting of that, plus the updated board data. From there we go in to the game rounds.

*All* data after the first join will be accepted on;
```
player.socket.on('game_update', function(data) {
        // state_machine function to be called
        state_machine.do_gameplay(data);
    });
```

So everything after join needs the 'game_update' header. And the `data_type` dictate how the data is handled serverside.

**Comment by timack** [comment]
Sounds perfect.

**Comment by sumnerfit** [comment]
Need to be able to restrict to one house and road per setup phase turn.
need a little more logic to prevent someone from placing 2 roads and then picking up the first thus leaving a floater
