### ISSUE TITLE
Can't build road.

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#346]
![image](https://user-images.githubusercontent.com/22135017/31858850-27e7db5c-b75e-11e7-923f-e9374bf015da.png)

I think (as the red player) I should be able to extend my road further up the coast but no ghost roads available

**Comment by akclint** [comment]
No, an opponent building blocks your road.  You can only build beyond if you already have something on the other side.  That is part of the original catan rules.

**Comment by sumnerfit** [comment]
Fair enough.  I thought I could keep building, just not benefit from longest road
