### ISSUE TITLE
Start Up Resources Allocation

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#35]
At the end of the start up phase, player needs to select one of their settlements. And they receive one resource from each adjacent tiles.

**Comment by Luke-Nukem** [comment]
Need to discuss with Alayn and Craig. May require an additional "action" for use in the API.

**Comment by timack** [comment]
Have added this as a function in game.js, have also created a test using mock objects. 
@akclint should there be some UI updates when these first resources are distributed? At the moment I guess they'll just show up in the players cards in the next game state update?
