### ISSUE TITLE
Allocate resources after dice roll

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#36]
After dice roll determine resource distribution and allocation to players and send with game update.

Remember robber could be blocking a resource tile

**Comment by Luke-Nukem** [comment]
Server-side game logic. Will assign to myself.

**Comment by timack** [comment]
@Luke-Nukem I'm keen to have a crack at this. Will help me get my head around the state machine. Are you ok with that?

**Comment by Luke-Nukem** [comment]
Totally fine by me. I'll make sure I sync my work with yours.

**Comment by timack** [comment]
i'm making a start in this now.

**Comment by timack** [comment]
Have created function and unit test. Still to do:

- [ ] Add to state machine
- [ ] Trigger and populate start of round modal

**Comment by timack** [comment]
@akclint Can we close this one now?
