### ISSUE TITLE
Use Dev Card - Monopoly

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#40]
Rules to be determined.

**Comment by sumnerfit** [comment]
Rules after discussions

In our version, monopoly needs to be played after the round starts but before other players can start using their cards. To this end, the players who do not have the monopoly card keep seeing the "waiting for other players to finish" window.  The player who has the card, can see the next rounds dice roll window and gets prompted whether they want to use the monopoly card. 

Yes: means player data needs to be resent with adjusted resource cards.
No : means a flag to close the window is sent and the turn progresses

**Comment by sumnerfit** [comment]
Somehow made ore = -1 when using monopoly card.... or introduced earlier
![image](https://user-images.githubusercontent.com/22135017/30039617-d9984ca8-9227-11e7-941d-6435cd35f4d0.png)
