### ISSUE TITLE
Robber on a seven

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#42]
If seven rolled everyone loses a random resource.
Display on interface what has happened.
Select a random tile to move the robber to

**Comment by timack** [comment]
@akclint do we also need to remove half the resource cards from someone if they have more than 7 cards when a 7 is rolled?

**Comment by AlaynC** [comment]
Yes, anytime someone has more than 7 cards, they lose half (rounded down to be in their favour)

**Comment by Luke-Nukem** [comment]
Server-side game logic. Will assign myself to this.

**Comment by timack** [comment]
@Luke-Nukem I can take a look at this one tonight if you like?

**Comment by timack** [comment]
Discussed with @akclint additional logic - 7 can only be rolled after someone had built a structure - not including the settlement from the start up sequence.
