### ISSUE TITLE
Dev Card - Road Building

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#44]
Allow the player to place two roads for free.

**Comment by sumnerfit** [comment]
I'm just writing notes as I go.

![image](https://user-images.githubusercontent.com/22135017/30301159-185232bc-97ad-11e7-9233-e0c96b685c16.png)

Placed two roads but resources didn't decrease as I did.

![image](https://user-images.githubusercontent.com/22135017/30301177-36ef96f6-97ad-11e7-96c9-a2f8711f28c2.png)

Road building card still there after it has been used.

![image](https://user-images.githubusercontent.com/22135017/30301215-8144d216-97ad-11e7-8b21-f8266ed7eb17.png)

**Comment by sumnerfit** [comment]
Two road_building cards fixed, 

Road building is not removed from the deck at any point so remains available in following turns

**Comment by timack** [comment]
@sumnerfit can you confirm this should be closed - pls reopen if I've got this wrong
