### ISSUE TITLE
Inter-player Resource Trading

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#55]
Allow player to player trading.

**Comment by timack** [comment]
Think we'll need to break this one down into sub issues:
- [ ] Interface update
- [ ] Trading API
- [ ] Extra server communication for Trading fulfilment

**Comment by sumnerfit** [comment]
Idea : We could have players communicate with each other and if a transaction is agreed on, both players send the transaction to the server.  Server fills the transaction if it gets two copies

**Comment by Luke-Nukem** [comment]
Rough outline:

* Players wanting to trade click button to open trade window
    * once `okay` is clicked, selected resources are sent as a data package to server which then sends details to other players
* Other players then have a "notification" show up in a designated area (tba)
    * has `accept` and `decline` buttons
    * if all players decline, that cancels the trade outright (hopefully allowing turns to progress without a trade holding it up)
* trades are early bird gets the worm style

Note: server no-longer needs a "trade" state.

**Comment by timack** [comment]
I think this is a shit hot solution and will work well in terms of gameplay.

**Comment by timack** [comment]
I'm Iceboxing this for now - we can look at it again post Week 8.
