### ISSUE TITLE
Compress Selenium code

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#69]
Compress the large number of driver creations down to a function and arrays to create the tests

**Comment by fishinsea2014** [comment]
Finished.

**Comment by timack** [comment]
@fishinsea2014 Can you create a Pull Request for this if it is ready to be merged into master. Probably best not to close the issue until your code is in master - if you could move this issue to the Review/QA column on ZenHub when you have created your PR that would be great. Anything not clear let me know.

**Comment by fishinsea2014** [comment]
Ok. Sorry to close this issue too early.

**Comment by timack** [comment]
@fishinsea2014  How are you getting on with this? Are you able to create the PR?

**Comment by timack** [comment]
@fishinsea2014 any update on this?

**Comment by timack** [comment]
@fishinsea2014 What's going on? Do you need help?

**Comment by timack** [comment]
Resolved now @fishinsea2014 has started scripting tests on Python.
