### ISSUE TITLE
Update Selenium to target master branch, not current public release.

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#70]
Find a way to:

- test against the master branch, not public release

- find a way for travis-ci to run the tests once a day at midnight so as not to interfere every time we commit code

**Comment by sumnerfit** [comment]
Selenium runs in a browser so it needs to test against a live project.  We can have a shadow copy of the master branch with selenium tests enabled.  This can be tested with a nightly cron job.  This leaves the master branch free of Selenium so tests run quickly.

**Comment by timack** [comment]
Resolved as per #118
