### ISSUE TITLE
HTML Templates for all game elements

### ISSUE THREAD

**Issue by AlaynC** [159356-1702-Extramural/capstone#73]
- Start Game
- Waiting for other players
- Start of turn (Dice roll and results)
- Maritime trade interface (bank)
- Domestic trade interface (players)
- Play knight interface
- Play Monopoly interface
- Play Year of Plenty interface
- Round result interface
- End of game interface

**Comment by timack** [comment]
Looks good - have merged in. Good to have this in place for when we come to build these features!
