### ISSUE TITLE
Rework Selenium to run as nightly tests (check if possible, and implement)

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#83]
Currently, having gui testing fire every time there is a branch published, a pull request actioned or an update made holds the testing up for around 5 minutes.  This test runs on 6 browsers and checks the title tag on the landing page.  Any relevant tests will push gui testing out to a long wait time.

For that reason, having nightly gui tests to check playability would still provide valuable information in a timely manner

**Comment by timack** [comment]
Did a little bit of research https://docs.travis-ci.com/user/cron-jobs/
Look like the build triggered by the cron job has an environment variable set - can we detect that somehow and use that to determine if the Selenium tests should be run.
https://docs.travis-ci.com/user/environment-variables/

**Comment by timack** [comment]
Have merged in update.
