### ISSUE TITLE
Add contact details to Google Doc

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#9]
Please you add your contact details to the doc in Google.

https://docs.google.com/document/d/18AEIPdl-y2uTPvFQBjD1UHW62OL6AWArqN0dThdD_gc/edit?usp=sharing

- [x] Tim
- [x] Jason
- [x] Alayn
- [x] Craig

Last person please close this issue.

**Comment by sumnerfit** [comment]
Google Doc contacts complete
