### ISSUE TITLE
Logic issues in setup

### ISSUE THREAD

**Issue by sumnerfit** [159356-1702-Extramural/capstone#97]
TODO:

- Render roads of other players during setup.
- Currently, road nodes are grabbed by splitting the div element on '_' , it works fine, should we be able to access a road node id on the client side during drag and drop?
- Needs logic to ensure road is connected to node in actions array. Currently, can manipulate game to place more than one road and then violate the house-road rule and end turn.

**Comment by timack** [comment]
Assume this should be closed? Re-open if not.
